### PR TITLE
Enable for languages other than Go

### PR DESCRIPTION
**Pull request by deltaidea**
Change language selector from `'go'` to `'*'`.

### CODE REVIEW

**Comment by deltaidea** [comment]
@dt Hey, I noticed you're not subscribed to this repo. Do you still use VS Code? If not, do you need help with maintenance of this repo?

**Comment by dt** [comment]
@deltaidea thanks for the fixes! I do still use vscode, but I'd completely forgotten about this extension. I'm subscribed to it now, but also happy to add more collaborators so I'm not a bottleneck to getting things merged.

**Comment by deltaidea** [comment]
Thanks a lot for this extension by the way! It's a minor convenience that adds up and makes me happy.

If you could bump the version and `vsce publish`, that would be great. 😄

**Comment by dt** [comment]
@deltaidea published as 0.0.6, thanks again!

**Pull request merged**
